[Pennylane]
title = "Pennylane jobs"
url = "https://jobs.lever.co/pennylane/"
entrySelector = ".posting"
titleSelector = ".posting h5"
linkSelector = ".posting a"

[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
